export const products = [
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone XL',
        price: 799,
        description: 'A large phone with one of the best screens',
        heading1: 'サンプルテキスト',
        heading2: 'サンプルテキスト',
        heading3: 'サンプルテキスト',
        headingtext1: ' example example example example example example example',
        headingtext2: ' test test test test test test test',
        headingtext3: ' text text text text text text text text text ',
    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone Mini',
        price: 699,
        description: 'A great phone with one of the best cameras',
        heading1: 'サンプルテキスト',
        heading2: 'サンプルテキスト',
        heading3: 'サンプルテキスト',
        headingtext1: ' example example example example example example example',
        headingtext2: ' test test test test test test test',
        headingtext3: ' text text text text text text text text text ',
    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone Standard',
        price: 299,
        description: '',
        heading1: 'サンプルテキスト',
        heading2: 'サンプルテキスト',
        heading3: 'サンプルテキスト',
        headingtext1: ' example example example example example example example',
        headingtext2: ' test test test test test test test',
        headingtext3: ' text text text text text text text text text ',
    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone Special',
        price: 999,
        description: '',
        heading1: 'サンプルテキスト',
        heading2: 'サンプルテキスト',
        heading3: 'サンプルテキスト',
        headingtext1: ' example example example example example example example',
        headingtext2: ' test test test test test test test',
        headingtext3: ' text text text text text text text text text ',
    }
];